FROM python:3.14

WORKDIR /frontend

COPY . .
#COPY .env .env

RUN pip install --no-cache-dir --upgrade -r requirements.txt

EXPOSE 5000

CMD ["gunicorn", "-k", "eventlet", "-w", "1", "-b", "0.0.0.0:5008", "--access-logfile", "-", "--error-logfile", "-", "app:create_app()"]